version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
